ECommiersMarket/Controllers/AddGroupsController.cs
using ECommiersMarket.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommiersMarket.Controllers
{
    public class AddGroupsController : Controller
    {
        ZahraMarketEntities db = new ZahraMarketEntities();
        // GET: AddGroups
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ADD_gROUPS(MainGroup MG)
        {
            MG.IsDeleted = false;
            var ff = db.MainGroups.OrderByDescending(x => x.Id).FirstOrDefault();

            HttpPostedFileBase ProPicture = Request.Files["pi_path"];
            if (ff == null)
            {
                MG.pi_path = "/Uploads/ServicesAtt/" + "1";
            }
            else
            {
                MG.pi_path = "/Uploads/ServicesAtt/" + (ff.Id + 1);

            }
            if (!Directory.Exists(Server.MapPath(MG.pi_path)))
                Directory.CreateDirectory(Server.MapPath(MG.pi_path));
            MG.pi_path = MG.pi_path + "/" + MG.GroupName+ ".jpg";
            ProPicture.SaveAs(Server.MapPath(MG.pi_path));

            db.MainGroups.Add(MG);
            db.SaveChanges();
            TempData["success"] = "تم حفظ البيانات بنجاح";

            var Groupps = db.MainGroups.ToList();
            return View("Index", Groupps);
        }
    }
}

ECommiersMarket/Views/AddGroups/Index.cshtml
@{
    ViewBag.Title = "تسجيل فئة جديدة ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p style="direction:ltr ">
    <a color:black; class="btn btn-outline-success" href="~/SubGroups/Index">الرجوع للقائمة   </a>
</p>

@using (Html.BeginForm("ADD_gROUPS", "AddGroups", FormMethod.Post, new { enctype = "multipart/form-data" }))
{


    <div class="form-control ">
        <div class="col-12">
            <label for="GroupName" class="form-label">إسم الفئه  :  </label>
            <input type="text" class="form-control" id="GroupName" name="GroupName" placeholder="المجموعة " required>
            <div class="invalid-feedback">
            </div>
            <br>
            <label for="pi_path" class="form-label">  صورة الفئه  </label>
            <input type="file" class="form-control" id="pi_path" name="pi_path" placeholder="صورة " required>
            <div class="invalid-feedback">

            </div>
            <br>
            <div class="mb-3">
                <button class="btn btn-primary w-100 waves-effect waves-light" type="submit"> حفظ  </button>
            </div>
        </div>
    </div>
}